[build-system]
build-backend = 'mesonpy'
requires = [
    "meson-python",
    "wheel",
    "numpy"
]

[project]
name = "physicaldtype"
version = "0.1.0"
description = "A simple tutorial package"
requires-python = ">=3.11,<=3.14"
authors = [
    {name = "Riku", email = "rikusaka03@gmail.com"},
]
dependencies = [
    "numpy>=2.4",
]

